version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - database

  frontend:
    build:
      context: ./my-hotel 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'myHotel'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      
